# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 12:33
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id_award', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(blank=True, default='lol', max_length=100)),
                ('releaseDate', models.DateField(blank=True, default=datetime.date.today)),
                ('runtime', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prevViews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id_grant', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('birthDate', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('episodes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('title', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('releaseDate', models.DateField(blank=True, default=datetime.date.today)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('awards', models.ManyToManyField(blank=True, through='series.Grant', to='series.Award')),
                ('company', models.ManyToManyField(blank=True, to='series.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avViews', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('ratingF', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ratingI', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('votesF', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('votesI', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='series.Person')),
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('series.person',),
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='series.Person')),
                ('id_creator', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('series.person',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='series.Person')),
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('series.person',),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='grant',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, to='series.Actor'),
        ),
        migrations.AddField(
            model_name='series',
            name='creators',
            field=models.ManyToManyField(blank=True, to='series.Creator'),
        ),
        migrations.AddField(
            model_name='series',
            name='directors',
            field=models.ManyToManyField(blank=True, to='series.Director'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('series', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([('series', 'season', 'number')]),
        ),
    ]
