# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='releaseDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='series',
            name='website',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
