# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20161121_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingF', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('ratingI', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('votesF', models.IntegerField(default=0)),
                ('votesI', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='episode',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='series',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
