# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20161122_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.Person')),
                ('id_creator', models.IntegerField(default=0)),
            ],
            bases=('series.person',),
        ),
    ]
