# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.Person')),
                ('id_actor', models.IntegerField(default=0)),
            ],
            bases=('series.person',),
        ),
        migrations.CreateModel(
            name='StatEpisode',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.Stat')),
                ('views', models.IntegerField(default=0)),
            ],
            bases=('series.stat',),
        ),
        migrations.CreateModel(
            name='StatSeries',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.Stat')),
                ('views', models.IntegerField(default=0)),
            ],
            bases=('series.stat',),
        ),
    ]
